
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdigital_setup.h"

/*
* The configuration table for devices
*/

XDigital_setup_Config XDigital_setup_ConfigTable[XPAR_XDIGITAL_SETUP_NUM_INSTANCES] =
{
	{
		XPAR_DIGITAL_SETUP_0_DEVICE_ID,
		XPAR_DIGITAL_SETUP_0_S_AXI_CONTROL_BASEADDR
	}
};


