
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xpwm_scaling.h"

/*
* The configuration table for devices
*/

XPwm_scaling_Config XPwm_scaling_ConfigTable[XPAR_XPWM_SCALING_NUM_INSTANCES] =
{
	{
		XPAR_PWM_SCALING_0_DEVICE_ID,
		XPAR_PWM_SCALING_0_S_AXI_CONTROL_BASEADDR
	}
};


