
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xatan_saturation.h"

/*
* The configuration table for devices
*/

XAtan_saturation_Config XAtan_saturation_ConfigTable[XPAR_XATAN_SATURATION_NUM_INSTANCES] =
{
	{
		XPAR_ATAN_SATURATION_0_DEVICE_ID,
		XPAR_ATAN_SATURATION_0_S_AXI_CONTROL_BASEADDR
	}
};


